---
# These 2 task will ensure that the zabbix client is installed before changing the configuration
- name: Ensure zabbix agent is installed - apt
  ansible.builtin.apt:
    name: "{{ new_vm_zabbix_package }}"
    state: present
  delegate_to: "{{ new_vm_ip }}"
  when: "'debian' in new_vm_os_type"

- name: Ensure zabbix agent is installed - rpm
  ansible.builtin.yum:
    name: "{{ new_vm_zabbix_package }}"
    state: present
  delegate_to: "{{ new_vm_ip }}"
  when: "'debian' not in new_vm_os_type"

# Zabbix conf is applied by lineinfile. It doesn't need a full template.
# Our zabbix infrastructure is based on the 3 environment prod, qa and dev.
# Each have their own metadata group to allow zabbix client to autoregister themselves.
# Each metadata group name is defined in the 'Set variables for ENVIRONMENT'
# Then once the zabbix agent service start it will contact the server and autoregister itself in his own environment group.
- name: OS | Set {{ new_vm_name }} Zabbix config file
  delegate_to: "{{ new_vm_ip }}"
  register: new_vm_set_zabbix_conf_output
  loop:
    - { regexp: '^Server=127', line: 'Server={{ new_vm_zabbix_server }}' }
    - { regexp: '^ServerActive=127', line: 'ServerActive={{ new_vm_zabbix_server }}:{{ new_vm_zabbix_port }}' }
    - { regexp: '^Hostname=Za', line: 'Hostname={{ new_vm_name }}' }
    - { regexp: '^# HostMetadata=', line: 'HostMetadata={{ new_vm_zabbix_metadata_group }}' }
    - { regexp: '^# HostInterface=', line: "HostInterface={{ new_vm_ip }}" }
  ansible.builtin.lineinfile:
    path: "{{ new_vm_zabbix_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"

# Zabbix client in redhat allow the client port during install.
# But from experience it's best to have a task to check that the port has the right context applied.
- name: OS | Allow Zabbix client port in {{ new_vm_name }} SELinux
  when: new_vm_os_type != 'debian'
  delegate_to: "{{ new_vm_ip }}"
  register: new_vm_allow_zabbix_sel_output
  community.general.seport:
    ports: 10050
    proto: tcp
    setype: zabbix_port_t
    state: present

- name: OS | Allow Zabbix client service in firewalld
  when: new_vm_os_type != 'debian'
  delegate_to: "{{ new_vm_ip }}"
  register: new_vm_allow_zabbix_fwd_output
  ansible.posix.firewalld:
    service: zabbix-agent
    state: enable
    permanent: true
    immediate: true

# Enable and restart the agent service if the conf has been changed
# On first start the client will autoregister itself in the server.
- name: OS | Enable and restart {{ new_vm_name }} Zabbix agent
  ansible.builtin.systemd:
    name: "{{ new_vm_zabbix_package }}"
    enabled: yes
    state: restarted
  delegate_to: "{{ new_vm_ip }}"
  register: new_vm_add_restart_zabbix_client_output
  when: new_vm_set_zabbix_conf_output.changed
