---
- name: Upgrade hypervisor
  block:
    - name: Upgrade pve hypervisor
      register: pve_upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: full

  rescue:
    - name: Send a notification on failure
      delegate_to: localhost
      community.general.mail:
        from: "{{ notification_sender }}"
        to: "{{ notification_email }}"
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user | default(omit) }}"
        password: "{{ smtp_password | default(omit) }}"
        subject: "PVE Hypervisor upgrade FAILURE - {{ inventory_hostname }}"
        body: |
          ---------------------------
          {{ inventory_hostname }} - apt upgrade FAILED
          ---------------------------
          {{ pve_upgrade | to_nice_yaml }}

    - name: Exit playbook
      ansible.builtin.fail:
        msg: "PVE Hypervisor upgrade FAILURE"

##### End of block - Upgrade hypervisor

- name: Display pve upgrade output
  when: enable_debug | default('false') | bool
  debug:
    var: pve_upgrade.stdout_lines

- name: Check if reboot is necessary
  changed_when: reboot_check.stdout | length > 0
  failed_when: reboot_check.stderr | length > 0
  register: reboot_check
  command: needrestart -r a -p
