---
NITIAL VERIFICATIONS #####################################################################
# This part is all the task that verify value set for the different variables.
# Instead of a single assert task, each variable has its own assert task for better visualisation.

- name: Verifications block
  block:
    # This task will fail if the VM does not exist. (This is the expected result, which is why ignore_errors = true is set)
    # If the VM does exist, the task will not fail, but the output will capture the VM info and reuse it in the next task
    - name: Check if the VM exist
      ignore_errors: true
      community.proxmox.proxmox_kvm:
        api_user: "{{ pve_api_user }}"
        api_token_id: "{{ pve_api_token }}"
        api_token_secret: "{{ pve_api_secret }}"
        api_host: "{{ pve_api_node }}"
        name: "{{ new_vm_name }}"
        state: current
      register: check_vm_status

    # This will fail based on check_vm_status output if the vmid is defined (meaning the VM exist)
    # the task will fail and stop the playbook to avoid redeploying on the same VM.
    - name: Fail and stop the deployment if the VM already exist in the cluster
      ansible.builtin.fail:
        msg: "DEPLOYMENT ABORTED - VM: {{ new_vm_name }} exist in the cluster with VMID: {{ check_vm_status.vmid }}"
      when: check_vm_status.vmid is defined

    # Run check on all the mandatory variables to make sure the content match expected result and also make sure they have been defined.
    - name: Check the name (VM Name) is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_name is defined
          - new_vm_name is not match ('^[0-9]')
          - new_vm_name is match ('^[a-zA-Z0-9-]+$')
        fail_msg: "ERROR: Variable new_vm_name MUST be defined. The VM name MUST NOT start by a number, only dashes are allowed"
    - name: Check the cpu variables is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_cpu is defined
          - new_vm_cpu | int in [1, 2, 4, 8, 12, 16, 20, 24, 32, 48, 64, 72, 128]
        fail_msg: "ERROR - CPU must be one of: 1,2,4,8,12,16,20,24,32,48,64,72,128 (new_vm_cpu={{ new_vm_cpu }})"
    - name: Check the core variables is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_sockets is defined
          - new_vm_sockets | int in [1, 2, 4]
        fail_msg: "ERROR - Sockets must be one of: 1, 2 or 4 (new_vm_sockets={{ new_vm_sockets }})"
    - name: Check CPU/socket divisibility
      ansible.builtin.assert:
        that:
          - new_vm_cpu | int % new_vm_sockets | int == 0
        fail_msg: "ERROR - CPU/sockets divisibility is not correct"
    - name: Check the ram variables is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_memory is defined
          - new_vm_memory is match('^[0-9]{4,}$')
        fail_msg: "ERROR - new_vm_memory has to be a number only (4 digit min), new_vm_memory=8192 (8G), new_vm_memory=32768 (32G)..."
    - name: Check the disk variables is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_filesystem_size is defined
          - new_vm_filesystem_size is match('^[0-9]+$')
        fail_msg: "ERROR - new_vm_filesystem_size has to be a number only, like new_vm_filesystem_size=300. The size is in GB"
    - name: Check the os variable is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_os_type is defined
          - new_vm_os_type in ['rhel', 'debian', 'rocky']
        fail_msg: "ERROR - OS options are new_vm_os_type=rocky (RockyLinux9), rhel (RedHat9), debian (Debian13)"
    - name: Check the environment variable is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_environment is defined
          - new_vm_environment in ['prod', 'dev', 'qa']
        fail_msg: "ERROR - OS options are new_vm_os_type=rocky (RockyLinux9), rhel (RedHat9), debian (Debian13)"
    - name: Check the report type variable is in allowed value
      ansible.builtin.assert:
        that:
          - new_vm_report_type is defined
          - new_vm_report_type in ['email', 'output', 'both', 'none']
        fail_msg: "ERROR - Report type are new_vm_report_type=email, output, both or none"

  rescue:
    - name: Email notification on failure
      community.general.mail:
        from: "{{ notification_sender }}"
        to: "{{ notification_email }}"
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user | default(omit) }}"
        password: "{{ smtp_password | default(omit) }}"
        subject: "Ansible automation - FAILURE - {{ new_vm_name }} deployment aborted"
        secure: "{{ smtp_sec_mode | default ('starttls') }}"
        body: |
          ---------------------------
          {{ new_vm_name }} - Deployment aborted
          ---------------------------
          Ansible FAILED to deploy {{ new_vm_name }}
          Date: {{ ansible_date_time.date }}
          Time: {{ ansible_date_time.time }} {{ ansible_date_time.tz }}

          One of the required variables for deployment is not set with the appropriate value.
          Review your playbook and resubmit.
          Deployment exited and nothing was done.
    - name: Exit playbook
      ansible.builtin.fail:
        msg: "ERROR - Deployment aborted - One of the required variables for deployment is not set with the appropriate value"
