---
# tasks file
#
- name: Run initial checks
  include_tasks: 1_initial_checks.yml

- name: Set environmeent variables
  include_tasks: 2_set_variables.yml

- name: Clone guest
# Clone the template,
# Update the hardware/network conf and reboot to apply changes.
# If the guest exist most of the task will not run, check the README.
  include_tasks: 3_deploy_host.yml

- name: Wait for all guest to be available
  wait_for_connection:
  delegate_to: "{{ new_vm_ip }}"

- name: Update guest hostname, packages, and filesystems
  include_tasks: 4_update_guest.yml

- name: Update guest disk space
  when:
    - new_vm_filesystem_size is defined
    - new_vm_filesystem_size | int > 0
  include_tasks: 5_update_diskspace.yml

- name: Set Zabbix configuration
# Only if set_zabbix is set to yes in defaults variables.
# You need to have Zabbix autoregistration configured.
# And the condition based on the Host metadata value.
  include_tasks: 5_zabbix_configuration.yml
  when: set_zabbix | default('true') | bool

########### REPORTS #######################################################################
# There is 4 choices in the report type. Email, ansible ouput, both or none.
- name: Deployment report
  debug:
    msg:
      - "{{ new_vm_name }} deployment is done"
      - "-----------------------------------"
      - "VMID: {{ new_vm_deployment_output.vmid }}"
      - "PVE_HOST: {{ new_vm_destination_node }}"
      - "CPU: {{ new_vm_cpu }}vcpu"
      - "RAM: {{ new_vm_memory }}MB"
      - "{% if new_vm_filesystem_size is defined and new_vm_filesystem_size | int > 0 %}OS_DRIVE: {{ new_vm_filesystem_size }}G additional space{% else %}OS_DRIVE: Default sizing, no added space{% endif %}"
      - "OS_TYPE: {{ new_vm_os_type }}"
      - "IP: {{ new_vm_ip }}"
      - "FQDN: {{ new_vm_name }}.{{ new_vm_domain }}"
  when: new_vm_report_type == 'output' or new_vm_report_type == 'both'

- name: Email report
  community.general.mail:
    from: "{{ notification_sender }}"
    to: "{{ notification_email }}"
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_user | default(omit) }}"
    password: "{{ smtp_password | default(omit) }}"
    subject: "Ansible automation - REPORT - {{ new_vm_name }} deployment successful"
    secure: "{{ smtp_sec_mode | default ('starttls') }}"
    body: |
      VMID: {{ new_vm_deployment_output.vmid }}
      PVE_HOST: {{ new_vm_destination_node }}
      CPU: {{ new_vm_cpu }}vcpu
      RAM: {{ new_vm_memory }}MB
      {% if new_vm_filesystem_size is defined and new_vm_filesystem_size | int > 0 %}
      OS_DRIVE: {{ new_vm_filesystem_size }}G additional space
      {% else %}
      OS_DRIVE: Default sizing, no added space
      {% endif %}
      OS_TYPE: {{ new_vm_os_type }}
      IP: {{ new_vm_ip }}
      FQDN: {{ new_vm_name }}.{{ new_vm_domain }}
  when: new_vm_report_type == 'email' or new_vm_report_type == 'both'
