---
- name: Patch all OS
  block:
    - name: PATCHING | Upgrade RPM based OS
      when: ansible_os_family == 'RedHat'
      register: rhel_patch_out
      ansible.builtin.yum:
        update_cache: true
        name: '*'
        state: latest

    - name: PATCHING | Update & upgrade Debian based OS
      when: ansible_os_family == 'Debian'
      register: deb_patch_out
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: PATCHING | DEBUG | Print patching output
      when:
        - (rhel_patch_out | default({})).changed or
          (deb_patch_out | default({})).changed
        - print_patching_output | default('false') | bool
      ansible.builtin.debug:
        msg: |
          {% if ansible_os_family == 'RedHat' %}
          {{ rhel_patch_out.results }}
          {% elif ansible_os_family == 'Debian' %}
          {{ deb_patch_out.stdout_lines }}
          {% else %}
          OS familly not recognized
          {% endif %}

    - name: PATCHING | Clean up yum cache
      when:
        - ansible_os_family == 'RedHat'
        - enable_pmcache_cleanup | default('false') | bool
      register: yum_clean_out_result
      changed_when: yum_clean_out_result.rc == 0
      failed_when: yum_clean_out_result.rc != 0
      ansible.builtin.command: "yum clean all"

    - name: PATCHING | Clean up apt cache
      when:
        - ansible_os_family == 'Debian'
        - enable_pmcache_cleanup | default('false') | bool
      ansible.builtin.apt:
        clean: true

  rescue:
    - name: PATCHING | Email notification on failure
      delegate_to: localhost
      community.general.mail:
        from: "{{ notification_sender }}"
        to: "{{ notification_email }}"
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user | default(omit) }}"
        password: "{{ smtp_password | default(omit) }}"
        attach: "{{ ansible_log.files[0].path | default(omit) }}"
        subject: "PVE VM Upgrade - ERROR - {{ inventory_hostname }} patching failed"
        body: |
          ---------------------------
          {{ inventory_hostname }} - Upgrade FAILED
          ---------------------------
          Ansible FAILED to patch {{ inventory_hostname }}
          Date: {{ ansible_date_time.date }}
          Time: {{ ansible_date_time.time }} {{ ansible_date_time.tz }}
          Output:
          {% if ansible_os_family == 'RedHat' %}
          {{ rhel_patch_out | to_nice_json }}
          {% endif %}
          {% if ansible_os_family == 'Debian' %}
          {{ deb_patch_out | to_nice_json }}
          {% endif %}
