---
- name: REBOOT | Check is a reboot is necessary
  changed_when: needs_reboot_result.stdout | length > 0
  failed_when: needs_reboot_result.stderr | length > 0
  register: needs_reboot_result
  command: >
    {% if ansible_os_family == 'Debian' %}
    needrestart -r a -p
    {% elif ansible_os_family == 'RedHat' %}
    yum needs-restarting --reboothint
    {% else %}
    echo "OS familly not recognize"
    {% endif %}

- name: REBOOT | Gracefully stop all containers before reboot
  when: 
    - needs_reboot_result.rc != 0
    - podman_images_list is defined
    - podman_images_list | length > 0
  become_user: "{{ podman_user }}"
  loop: "{{ podman_images_list }}"
  loop_control:
    label: "{{ item.name }}"
  systemd:
    name: "{{ item.scr }}"
    scope: user
    state: stopped

- name: REBOOT | Reboot the host if required
  when: needs_reboot_result.rc != 0
  register: new_kernel
  reboot:

- name: REBOOT | Wait for all host to be available before moving on
  when: needs_reboot_result.rc != 0
  register: wait_for_host
  wait_for_connection:
    timeout: "{{ after_reboot_delay | default('600') }}"
