---
# ansible_ssh_common_args:            # Allow ansible to log in on the host IP to finish the deployment.
# new_vm_ip:                          # The IP MUST match the subnet in which the guest will be deployed
# new_vm_name:                        # The VM name will be used as a hostname
# new_vm_cpu:                         # Total number of vCPU for the guest
# new_vm_sockets:                     # Total number of socket on the hypervisor (equal amount of vCPU will be assign per socket)
# new_vm_memory:                      # Total amount of RAM in MB
# new_vm_filesystem_size:             # Total amount of Gigabyte added to the host at deployment
# new_vm_start_on_boot:               # Default false - autostart the VM after an hypervisor reboot
# new_vm_environment:                 # Set the environment used for deployment: prod, qa or dev
# new_vm_os_type:                     # Set the OS type: debian, rocky or rhel
# new_vm_report_type:                 # Set the final report type: email, output, both or none
# new_vm_destination_node:            # Set the destination hypervisor that will host the new guest
# new_vm_guest_interface_type:        # Set the type of network interface for the new guest
# new_vm_guest_interface_name:        # Set the name of the network interface for the new guest
# new_vm_guest_interface_fw:          # Boolean - Enable/Disable proxmox firewall on the network interface
# set_zabbix:                         # Boolean - Default enabled - Enable/disable zabbix config setup
# # Set the account id created at deployment by cloud init to allow ansible automation. Password is protected with a vault encryption.
# proxmox_cloud_init_username:
# proxmox_cloud_init_password: !vault |
#     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
#     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
# proxmox_cloud_init_sshkey: "ssh-ed25519 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# notification_sender:                # Email used in the from field
# notification_email:                 # Email used as destination
