---
# https://github.com/RedHatOfficial/ansible-role-rhel9-cis_server_l1
- name: CIS Red Hat Enterprise Linux 9 Benchmark for Level 1 - Server
  hosts: all
  ignore_errors: true
  become: true
  gather_facts: true
  pre_tasks:
    - name: Ensure --limit is used
      run_once: true
      ansible.builtin.assert:
        that:
          - ansible_limit is defined
  tasks:
    - name: Apply CIS Lv1 Server RHEL 9
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == '9'
      register: cis_run_rhel9
      ansible.builtin.include_role:
        name: ansible-role-rhel9-cis_server_l1
